const selectedGrade = document.getElementById('grade');
const display = document.getElementById('courses-display');
const paragraphGrade = display.querySelector('p');
const mathGradeInfo = ['Bij AfterSkool<span class="mr-span">metRyvi</span> leggen we de basis voor rekenvaardigheden al bij de allerkleinsten. Onze interactieve en speelse oefeningen zijn speciaal ontworpen voor peuters, zodat zij op een leuke manier cijfers leren herkennen en eenvoudige rekenconcepten begrijpen.<br>Met kleurrijke en boeiende activiteiten maken we het leren van getallen een spannend avontuur. Peuters leren tellen, eenvoudige vormen herkennen en beginnen met basisbegrippen zoals meer en minder. Onze aanpak stimuleert nieuwsgierigheid en maakt het leerproces leuk en motiverend.','Met vrolijke en kleurrijke activiteiten leren kinderen in groep 1 cijfers herkennen, tellen en eenvoudige vormen benoemen. Ze ontdekken de magie van getallen door spelletjes die speciaal zijn afgestemd op hun leeftijd en ontwikkelingsniveau. Onze aanpak zorgt ervoor dat kinderen spelenderwijs leren, nieuwsgierig blijven en plezier hebben in het leerproces. <br>AfterSkool<span class="mr-span">metRyvi</span> helpt kinderen in groep 1 om zelfvertrouwen op te bouwen in hun rekenvaardigheden en een positieve houding ten opzichte van leren te ontwikkelen. Samen zetten we de eerste stappen in de fascinerende wereld van rekenen!',
                        'Bij AfterSkool<span class="mr-span">metRyvi</span> bouwen kinderen voort op hun basisvaardigheden in rekenen. Ze leren tellen tot hogere getallen, vergelijken hoeveelheden en maken eenvoudige sommen. Met kleurrijke en boeiende oefeningen ontdekken ze de wereld van getallen en ontwikkelen ze een dieper begrip van rekenconcepten. Onze speelse aanpak maakt leren leuk en stimuleert kinderen om nieuwsgierig te blijven. AfterSkool<span class="mr-span">metRyvi</span> helpt kinderen in groep 2 om zelfvertrouwen op te bouwen en een stevige basis te leggen voor hun verdere rekenontwikkeling.','In groep 3 helpt AfterSkool<span class="mr-span">metRyvi</span> kinderen om hun rekenvaardigheden verder te ontwikkelen. Ze leren optellen en aftrekken met grotere getallen, herkennen patronen en beginnen met eenvoudige vermenigvuldigingen. Onze interactieve spelletjes en oefeningen maken rekenen boeiend en leuk. Door spelenderwijs te leren, bouwen kinderen vertrouwen op in hun rekenvaardigheden en ontwikkelen ze een positieve houding ten opzichte van rekenen. AfterSkool<span class="mr-span">metRyvi</span> zorgt ervoor dat kinderen in groep 3 een stevige basis hebben voor hun verdere rekenontwikkeling.',
                        'Bij AfterSkool<span class="mr-span">metRyvi</span> leren kinderen in groep 4 de basis van vermenigvuldigen en delen. Ze oefenen met tafels en ontdekken hoe ze deze vaardigheden in het dagelijks leven kunnen toepassen. Onze interactieve oefeningen en spelletjes maken abstracte concepten begrijpelijk en leuk. Kinderen ontwikkelen hun rekenvaardigheden en bouwen zelfvertrouwen op door spelenderwijs te leren. AfterSkool<span class="mr-span">metRyvi</span> helpt kinderen in groep 4 om een solide basis te leggen voor meer geavanceerde rekenvaardigheden in de toekomst.',
                        'In groep 5 verdiepen kinderen hun rekenvaardigheden bij AfterSkool<span class="mr-span">metRyvi</span>. Ze leren breuken en decimalen begrijpen en toepassen, en oefenen met meer complexe vermenigvuldigingen en delingen. Onze interactieve oefeningen maken abstracte concepten begrijpelijk en leuk. Kinderen ontwikkelen hun probleemoplossende vaardigheden en bouwen zelfvertrouwen op door spelenderwijs te leren. AfterSkool<span class="mr-span">metRyvi</span> zorgt ervoor dat kinderen in groep 5 goed voorbereid zijn op de volgende stappen in hun rekenontwikkeling.',
                        'Bij AfterSkool<span class="mr-span">metRyvi</span> gaan kinderen in groep 6 aan de slag met geavanceerdere rekenvaardigheden zoals percentages, verhouding en meetkunde. Ze oefenen met het toepassen van deze vaardigheden in verschillende situaties. Onze interactieve oefeningen en spelletjes maken abstracte concepten begrijpelijk en leuk. Kinderen ontwikkelen hun analytische vaardigheden en bouwen zelfvertrouwen op door spelenderwijs te leren. AfterSkool<span class="mr-span">metRyvi</span> helpt kinderen in groep 6 om een solide basis te leggen voor meer geavanceerde rekenvaardigheden in de toekomst.',
                        'In groep 7 gaan kinderen bij AfterSkool<span class="mr-span">metRyvi</span> dieper in op algebra, breuken, en decimale getallen. Ze leren complexe problemen op te lossen en passen hun rekenvaardigheden toe in uitdagende situaties. Onze interactieve oefeningen en spelletjes maken abstracte concepten begrijpelijk en leuk. Kinderen ontwikkelen hun kritische denkvaardigheden en bouwen zelfvertrouwen op door spelenderwijs te leren. AfterSkool<span class="mr-span">metRyvi</span> zorgt ervoor dat kinderen in groep 7 goed voorbereid zijn op de laatste stappen van hun basisschool rekenontwikkeling.',
                        'Bij AfterSkool<span class="mr-span">metRyvi</span> bereiden we kinderen in groep 8 voor op de middelbare school. Ze oefenen met geavanceerde rekenvaardigheden zoals algebra, meetkunde, en statistiek. Onze interactieve oefeningen en spelletjes maken abstracte concepten begrijpelijk en leuk. Kinderen ontwikkelen hun probleemoplossende vaardigheden en bouwen zelfvertrouwen op door spelenderwijs te leren. AfterSkool<span class="mr-span">metRyvi</span> helpt kinderen in groep 8 om zelfverzekerd en goed voorbereid de overstap naar de middelbare school te maken.'
];


selectedGrade.addEventListener('change', () => {
        paragraphGrade.innerHTML = mathGradeInfo[selectedGrade.value];
});

selectedGrade.addEventListener('blur', () => {
    paragraphGrade.innerHTML = mathGradeInfo[selectedGrade.value];
});



